name: test_app
description: "Test app for Smart Pin Doorlock Widget"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
#  smart_pin_doorlock:
#    git:
#      url: git@github.com:ones-studios/os-smart-pin-doorlock.git
#      path: smart_pin_doorlock
#      ref: master #project
  smart_pin_doorlock:
    path: ../smart_pin_doorlock
      
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
