name: "smart_pin_doorlock"
description: "A description of your project"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  flutter_modular: ^5.0.3
  mockito: ^5.4.0
  getwidget: ^4.0.0
  sqflite: ^2.3.2
  intl: ^0.17.0
  provider: ^6.0.2
  #framework_contracts_flutter:
  #  git:
  #    url: git@github.com:ones-studios/os-framework-contracts-flutter.git
  #    path: framework_contracts_flutter
  #    ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.2

flutter:
