name: test_app
description: "Test app for {{ cookiecutter.project_name }} Widget"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  {{ cookiecutter.project_name|lower|replace(' ', '_') }}:
    git:
      url: git@github.com:discovery-ltd/os-{{ cookiecutter.project_name|lower|replace(' ', '-') }}-flutter.git
      path: {{ cookiecutter.project_name|lower|replace(' ', '_') }}
      ref: master #project
      
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
