name: Setup repository
on:
  push:
    paths:
      - cookiecutter.json
jobs:
  setup:
    name: Initialize repository
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: write
      checks: write
      deployments: write
      pull-requests: write
      statuses: write
    steps:
      - name: Do not run scaffolding on template repository
        shell: bash
        run: |
          curl --silent -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.baptiste-preview+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq --exit-status '.is_template == false';
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.ONES_STUDIOS_GITHUB_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Configure netrc for api.github.com
        uses: extractions/netrc@v1
        with:
          machine: api.github.com
          username: disco-bot
          password: ${{ secrets.ONES_STUDIOS_GITHUB_TOKEN }}
      - name: Configure netrc for github.com
        uses: extractions/netrc@v1
        with:
          machine: github.com
          username: disco-bot
          password: ${{ secrets.ONES_STUDIOS_GITHUB_TOKEN }}
      - uses: ruby/setup-ruby@v1
        name: Configure ruby 2.6
        with:
          ruby-version: 2.6
      - name: Configure gradle credentials
        run: |
          #!/usr/bin/env bash
          set -ex
          MAVEN_USERNAME=mronestonyo
          MAVEN_PASSWORD=${{ secrets.ONES_STUDIOS_GITHUB_TOKEN }}
          # gradle deployment deets
          mkdir -p ~/.gradle
          touch ~/.gradle/gradle.properties
          echo "mavenUsername="$MAVEN_USERNAME > ~/.gradle/gradle.properties
          echo "mavenPassword="$MAVEN_PASSWORD >> ~/.gradle/gradle.properties
      - name: Install dependencies
        run: pip install cookiecutter
      - name: Scaffolding repository
        run: |
          cp cookiecutter.json template/cookiecutter.json
          cookiecutter template --no-input --output-dir ./cookiecutter-temp
      - name: Prepare root directory
        shell: bash
        run: |
          find ./ -maxdepth 1 \
          ! -name '.git' \
          ! -name '.gitignore' \
          ! -name 'cookiecutter-temp' \
          ! -name '.' \
          ! -exec rm -rf {} +
      - name: Move files to root
        shell: bash
        run: |
          rsync -a ./cookiecutter-temp/template/. .
          rm -rf ./cookiecutter-temp/
#      - name: Run intial scripts
#        run: |
#          ./pub_get.sh
      - name: Commit the changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git checkout master && \
          git add . && \
          git commit -m 'Initialised repository' && \
          git push origin HEAD:master
